# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_auto_20170811_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_logo',
        ),
    ]
