# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0007_auto_20170902_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='new_column',
            new_name='album_logo',
        ),
    ]
